kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    node-role.fluidos.eu/resources: "true"
    node-role.fluidos.eu/worker: "true"
- role: worker
  labels:
    node-role.fluidos.eu/resources: "true"
    node-role.fluidos.eu/worker: "true"

