apiVersion: v1
kind: Namespace
metadata:
  name: sensors
---
apiVersion: v1
kind: Service
metadata:
  namespace: sensors
  name: temp-sensor
  labels:
    app: temp-sensor
    nodecore.fluidos.eu/flavor-service-endpoint: "true"
spec:
  type: NodePort
  selector:
    app: temp-sensor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
